Add makefile rules for capturing compilation errors and use that with a concrete example

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -20,13 +20,21 @@ TARGETS= \
 
 .SILENT: all
 
+ERRORS= \
+  no-copyctr.err
+
+# FAILS = $(ERRORS:.cc=)
+
+%.err : %.cc
+	-$(CC) $(CFLAGS) $(CPPFLAGS) $< -o /tmp/$@ 2> bin/$@ || true
+
 %: %.o
 	$(CC) $(CFLAGS) $(CPPFLAGS) $< -o bin/$@
 
-%.o: %.c 
+%.o: %.cc
 	$(CC) $(CFLAGS) $(CPPFLAGS) -c $<
 
-all: $(TARGETS)
+all: $(TARGETS) $(ERRORS)
 	cat HEADER.md > README.md
 	for bin in $(TARGETS); do \
 		echo $$bin; \
@@ -35,7 +43,7 @@ all: $(TARGETS)
 		echo "\`\`\`c++" >> README.md; \
 		cat $$bin.cc >> README.md; \
 		echo "\`\`\`" >> README.md; \
-		echo "Result: " >> README.md; \
+		echo "Result:" >> README.md; \
 		echo "\`\`\`bash" >> README.md; \
 		./$$bin; \
 		./$$bin > $$bin.out; \
@@ -43,7 +51,23 @@ all: $(TARGETS)
 		echo "\`\`\`" >> README.md; \
 		echo ""; \
 	done
+
+	@echo $(ERRORS)
+	for bin in $(ERRORS:.err=); do \
+		echo $$bin; \
+		echo ""; \
+		echo "# [$ssrc/$$bin.cc]($ssrc/$$bin.cc)" >> README.md; \
+		echo "\`\`\`c++" >> README.md; \
+		cat $$bin.cc >> README.md; \
+		echo "\`\`\`" >> README.md; \
+		echo "Result:" >> README.md; \
+		echo "\`\`\`bash" >> README.md; \
+		cat bin/$$bin.err >> README.md; \
+		echo "\`\`\`" >> README.md; \
+		echo ""; \
+	done
+
 	cat FOOTER.md >> README.md
 
 clean:
-	rm -df $(TARGETS) *~
+	rm -df $(TARGETS) *~ bin/*
